apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fastapi-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard"
  resources:
    requests:
      storage: 5Gi
  volumeName: fastapi-pvc
