# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.29.12
    # add a mount from /path/to/my/files on the host to /files on the node
  - role: worker
    image: kindest/node:v1.29.12
    extraMounts:
      - hostPath: Project/
        containerPath: /mnt/project
        selinuxRelabel: false
        # optional: set propagation mode (None, HostToContainer or Bidirectional)
        # see https://kubernetes.io/docs/concepts/storage/volumes/#mount-propagation
        # default None
        #
        # WARNING: You very likely do not need this field.
        #
        # This field controls propagation of *additional* mounts created
        # *at runtime* underneath this mount.
        #
        # On MacOS with Docker Desktop, if the mount is from macOS and not the
        # docker desktop VM, you cannot use this field. You can use it for
        # mounts to the linux VM.
        propagation: None
