apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  labels:
    app: fastapi
spec:
  selector:
    matchLabels:
      app: fastapi
  replicas: 1
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      containers:
        - name: fastapi
          image: python_uv:0.04
          ports:
            - containerPort: 8080
              name: fastapi
          volumeMounts:
            - name: fastapi-pv
              mountPath: /app

      volumes:
        - name: fastapi-pv
          persistentVolumeClaim:
            claimName: fastapi-pvc
