apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  type: ClusterIP
  ports:
    - name: fastapi
      protocol: TCP
      port: 8080
      targetPort: 8080
