[project]
name = "practice-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi==0.109.2",
    "pydantic>=2.11.3",
    "python-dotenv==1.0.1",
    "sqlalchemy>=2.0.41",
    "uvicorn[standard]>=0.34.2",
]
